-- MySQL Script generated by MySQL Workbench
-- Mon Sep 14 23:04:41 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema databanc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema databanc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `databanc` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `databanc` ;

-- -----------------------------------------------------
-- Table `databanc`.`adminis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `databanc`.`adminis` (
  `idadminis` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `departamento` VARCHAR(15) NOT NULL COMMENT '',
  PRIMARY KEY (`idadminis`)  COMMENT '',
  UNIQUE INDEX `idadminis_UNIQUE` (`idadminis` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `databanc`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `databanc`.`usuarios` (
  `idusuarios` INT NOT NULL COMMENT '',
  `name` VARCHAR(20) NOT NULL COMMENT '',
  `apellido1` VARCHAR(20) NOT NULL COMMENT '',
  `apellido2` VARCHAR(20) NOT NULL COMMENT '',
  `dni` VARCHAR(10) NOT NULL COMMENT '',
  `email` VARCHAR(30) NOT NULL COMMENT '',
  `direccion` VARCHAR(20) NOT NULL COMMENT '',
  `pass` VARCHAR(10) NOT NULL COMMENT '',
  `hash_pass` VARCHAR(255) NOT NULL COMMENT '',
  `idadminis` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idusuarios`)  COMMENT '',
  UNIQUE INDEX `idusuarios_UNIQUE` (`idusuarios` ASC)  COMMENT '',
  INDEX `fk_usuarios_adminis_copy11_idx` (`idadminis` ASC)  COMMENT '',
  CONSTRAINT `fk_usuarios_adminis_copy11`
    FOREIGN KEY (`idadminis`)
    REFERENCES `databanc`.`adminis` (`idadminis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `databanc`.`cuentas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `databanc`.`cuentas` (
  `idcuentas` INT NOT NULL COMMENT '',
  `num_cuenta` BIGINT(11) NOT NULL COMMENT '',
  `saldo_actual` FLOAT NOT NULL COMMENT '',
  `tipo` VARCHAR(10) NOT NULL COMMENT '',
  `idusuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idcuentas`)  COMMENT '',
  UNIQUE INDEX `idcuentas_UNIQUE` (`idcuentas` ASC)  COMMENT '',
  INDEX `fk_cuentas_usuarios1_idx` (`idusuario` ASC)  COMMENT '',
  CONSTRAINT `fk_cuentas_usuarios1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `databanc`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `databanc`.`reg_transacciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `databanc`.`reg_transacciones` (
  `idreg_transaciones` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fecha` DATE NOT NULL COMMENT '',
  `hora` TIME(3) NOT NULL COMMENT '',
  `tipo` VARCHAR(20) NOT NULL COMMENT '',
  `concepto` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`idreg_transaciones`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `databanc`.`ingresos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `databanc`.`ingresos` (
  `idingresos` INT NOT NULL COMMENT '',
  `saldo_i` FLOAT NOT NULL COMMENT '',
  `saldo_f` FLOAT NOT NULL COMMENT '',
  `importe` FLOAT NOT NULL COMMENT '',
  `idcuenta` INT NOT NULL COMMENT '',
  `idreg_transaccion` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idingresos`)  COMMENT '',
  UNIQUE INDEX `idingresos_UNIQUE` (`idingresos` ASC)  COMMENT '',
  INDEX `fk_ingresos_cuentas1_idx` (`idcuenta` ASC)  COMMENT '',
  INDEX `fk_ingresos_reg_ingresos1_idx` (`idreg_transaccion` ASC)  COMMENT '',
  CONSTRAINT `fk_ingresos_cuentas1`
    FOREIGN KEY (`idcuenta`)
    REFERENCES `databanc`.`cuentas` (`idcuentas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingresos_reg_ingresos1`
    FOREIGN KEY (`idreg_transaccion`)
    REFERENCES `databanc`.`reg_transacciones` (`idreg_transaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `databanc`.`traspasos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `databanc`.`traspasos` (
  `idtraspasos` INT NOT NULL COMMENT '',
  `saldo_A_i` FLOAT NOT NULL COMMENT '',
  `saldo_A_f` FLOAT NOT NULL COMMENT '',
  `saldoi_B_i` FLOAT NOT NULL COMMENT '',
  `saldof_B_f` FLOAT NOT NULL COMMENT '',
  `importe` FLOAT NOT NULL COMMENT '',
  `idcuenta_A` INT NOT NULL COMMENT '',
  `idcuenta_B` INT NOT NULL COMMENT '',
  `idreg_transaccion` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idtraspasos`)  COMMENT '',
  UNIQUE INDEX `idtraspasos_UNIQUE` (`idtraspasos` ASC)  COMMENT '',
  INDEX `fk_traspasos_cuentas1_idx` (`idcuenta_A` ASC)  COMMENT '',
  INDEX `fk_traspasos_cuentas2_idx` (`idcuenta_B` ASC)  COMMENT '',
  INDEX `fk_traspasos_reg_ingresos1_idx` (`idreg_transaccion` ASC)  COMMENT '',
  CONSTRAINT `fk_traspasos_cuentas1`
    FOREIGN KEY (`idcuenta_A`)
    REFERENCES `databanc`.`cuentas` (`idcuentas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_traspasos_cuentas2`
    FOREIGN KEY (`idcuenta_B`)
    REFERENCES `databanc`.`cuentas` (`idcuentas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_traspasos_reg_ingresos1`
    FOREIGN KEY (`idreg_transaccion`)
    REFERENCES `databanc`.`reg_transacciones` (`idreg_transaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `databanc`.`reg_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `databanc`.`reg_usuarios` (
  `idreg_usuarios` INT NOT NULL COMMENT '',
  `fecha` DATE NOT NULL COMMENT '',
  `hora` TIME(3) NOT NULL COMMENT '',
  `tipo` VARCHAR(20) NOT NULL COMMENT '',
  `idusuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idreg_usuarios`)  COMMENT '',
  UNIQUE INDEX `idregistros_UNIQUE` (`idreg_usuarios` ASC)  COMMENT '',
  INDEX `fk_registros_usuarios1_idx` (`idusuario` ASC)  COMMENT '',
  CONSTRAINT `fk_registros_usuarios1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `databanc`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
