-- MySQL Script generated by MySQL Workbench
-- Mon Sep 21 23:43:20 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db592883388
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db592883388
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db592883388` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `db592883388` ;

-- -----------------------------------------------------
-- Table `db592883388`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db592883388`.`usuarios` (
  `idusuario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(20) NOT NULL COMMENT '',
  `apellido1` VARCHAR(20) NOT NULL COMMENT '',
  `apellido2` VARCHAR(20) NOT NULL COMMENT '',
  `dni` VARCHAR(10) NOT NULL COMMENT '',
  `email` VARCHAR(40) NOT NULL COMMENT '',
  `direccion` VARCHAR(40) NOT NULL COMMENT '',
  `pass` VARCHAR(10) NOT NULL COMMENT '',
  `hash_pass` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`idusuario`)  COMMENT '',
  UNIQUE INDEX `idusuarios_UNIQUE` (`idusuario` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db592883388`.`cuentas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db592883388`.`cuentas` (
  `idcuenta` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `num_cuenta` BIGINT(11) NOT NULL COMMENT '',
  `saldo_actual` FLOAT NOT NULL COMMENT '',
  `tipo` VARCHAR(10) NOT NULL COMMENT '',
  `idusuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idcuenta`)  COMMENT '',
  UNIQUE INDEX `idcuentas_UNIQUE` (`idcuenta` ASC)  COMMENT '',
  INDEX `fk_cuentas_usuarios1_idx` (`idusuario` ASC)  COMMENT '',
  CONSTRAINT `fk_cuentas_usuarios1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `db592883388`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db592883388`.`reg_transacciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db592883388`.`reg_transacciones` (
  `idreg_transaccion` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fecha` DATE NOT NULL COMMENT '',
  `hora` TIME NOT NULL COMMENT '',
  `tipo` VARCHAR(20) NOT NULL COMMENT '',
  `concepto` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`idreg_transaccion`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db592883388`.`ingresos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db592883388`.`ingresos` (
  `idingreso` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `saldo_i` FLOAT NOT NULL COMMENT '',
  `saldo_f` FLOAT NOT NULL COMMENT '',
  `importe` FLOAT NOT NULL COMMENT '',
  `idcuenta` INT NOT NULL COMMENT '',
  `idreg_transaccion` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idingreso`)  COMMENT '',
  UNIQUE INDEX `idingresos_UNIQUE` (`idingreso` ASC)  COMMENT '',
  INDEX `fk_ingresos_cuentas1_idx` (`idcuenta` ASC)  COMMENT '',
  INDEX `fk_ingresos_reg_ingresos1_idx` (`idreg_transaccion` ASC)  COMMENT '',
  CONSTRAINT `fk_ingresos_cuentas1`
    FOREIGN KEY (`idcuenta`)
    REFERENCES `db592883388`.`cuentas` (`idcuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingresos_reg_ingresos1`
    FOREIGN KEY (`idreg_transaccion`)
    REFERENCES `db592883388`.`reg_transacciones` (`idreg_transaccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db592883388`.`traspasos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db592883388`.`traspasos` (
  `idtraspaso` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `saldo_A_i` FLOAT NOT NULL COMMENT '',
  `saldo_A_f` FLOAT NOT NULL COMMENT '',
  `saldo_B_i` FLOAT NOT NULL COMMENT '',
  `saldo_B_f` FLOAT NOT NULL COMMENT '',
  `importe` FLOAT NOT NULL COMMENT '',
  `idcuenta_A` INT NOT NULL COMMENT '',
  `idcuenta_B` INT NOT NULL COMMENT '',
  `idreg_transaccion` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idtraspaso`)  COMMENT '',
  UNIQUE INDEX `idtraspasos_UNIQUE` (`idtraspaso` ASC)  COMMENT '',
  INDEX `fk_traspasos_cuentas1_idx` (`idcuenta_A` ASC)  COMMENT '',
  INDEX `fk_traspasos_cuentas2_idx` (`idcuenta_B` ASC)  COMMENT '',
  INDEX `fk_traspasos_reg_ingresos1_idx` (`idreg_transaccion` ASC)  COMMENT '',
  CONSTRAINT `fk_traspasos_cuentas1`
    FOREIGN KEY (`idcuenta_A`)
    REFERENCES `db592883388`.`cuentas` (`idcuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_traspasos_cuentas2`
    FOREIGN KEY (`idcuenta_B`)
    REFERENCES `db592883388`.`cuentas` (`idcuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_traspasos_reg_ingresos1`
    FOREIGN KEY (`idreg_transaccion`)
    REFERENCES `db592883388`.`reg_transacciones` (`idreg_transaccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db592883388`.`reg_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db592883388`.`reg_usuarios` (
  `idreg_usuario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fecha` DATE NOT NULL COMMENT '',
  `hora` TIME NOT NULL COMMENT '',
  `tipo` VARCHAR(20) NOT NULL COMMENT '',
  `idusuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idreg_usuario`)  COMMENT '',
  UNIQUE INDEX `idregistros_UNIQUE` (`idreg_usuario` ASC)  COMMENT '',
  INDEX `fk_registros_usuarios1_idx` (`idusuario` ASC)  COMMENT '',
  CONSTRAINT `fk_registros_usuarios1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `db592883388`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db592883388`.`adminis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db592883388`.`adminis` (
  `idadmini` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `departamento` VARCHAR(15) NOT NULL COMMENT '',
  `idusuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idadmini`)  COMMENT '',
  UNIQUE INDEX `idadminis_UNIQUE` (`idadmini` ASC)  COMMENT '',
  INDEX `fk_adminis_usuarios1_idx` (`idusuario` ASC)  COMMENT '',
  CONSTRAINT `fk_adminis_usuarios1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `db592883388`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
